PRO ex24
xpts=FINDGEN(361)
ypts=[[SIN(xpts*!DTOR)], [COS(xpts*!DTOR)]]
PSOPEN, THICK=200, CHARSIZE=150, XOFFSET=2000
CS, SCALE=1
GSET, XMIN=0, XMAX=360, YMIN=-1, YMAX=1
GPLOT, X=xpts, Y=ypts, /LEGEND, LEGPOS=3, COL=[3, 18], LABELS=['Sine', 'Cosine']
AXES, XSTEP=30, XTITLE='Degrees', YSTEP=0.25, YTITLE='Amplitude', NDECS=2
PSCLOSE
END
