import plot_arcticaod_zonal
plot_arcticaod_zonal.plot(varn='TOTEXTTAU550')
plot_arcticaod_zonal.plot(varn='DUEXTTAU550')
plot_arcticaod_zonal.plot(varn='SUEXTTAU550')
plot_arcticaod_zonal.plot(varn='SSEXTTAU550')
plot_arcticaod_zonal.plot(varn='BCEXTTAU550')
plot_arcticaod_zonal.plot(varn='OCEXTTAU550')
plot_arcticaod_zonal.plot(varn='BREXTTAU550')
plot_arcticaod_zonal.plot(varn='NIEXTTAU550')

plot_arcticaod_zonal.plot(expid='merra2',varn='TOTEXTTAU',merra2=1)
plot_arcticaod_zonal.plot(expid='merra2',varn='DUEXTTAU',merra2=1)
plot_arcticaod_zonal.plot(expid='merra2',varn='SUEXTTAU',merra2=1)
plot_arcticaod_zonal.plot(expid='merra2',varn='SSEXTTAU',merra2=1)
plot_arcticaod_zonal.plot(expid='merra2',varn='OCEXTTAU',merra2=1)
plot_arcticaod_zonal.plot(expid='merra2',varn='BCEXTTAU',merra2=1)
