"""Module to get data from GEOS-5 generated netcdf files

Author: Parker A. Case
Changelog: Created 1/31/2019
"""
import numpy as np
import h5py

# How many days are there in each month again?
days = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
        '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
        '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31']
months = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
days_in_months = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]


def get_hourly_filenames(prefix, experiment, file_type, year, month, day, start_time):
    """Create a list of filenames for a given directory, simulation,
    filetype, year, and time of day

    Arguments:
    prefix -- the directory containing the files
    experiment -- name of the simulation
    file_type -- which collection ex. tavg2d_aer_x
    year -- which year to generate files for
    time -- time of day of files
    """
    files = []
    time = int(start_time[:-1])
    while time < 2400:
        files.append(prefix + experiment + '.' + file_type + '.' + year +\
                month + day + '_' + str(time).zfill(4) + 'z.nc4')
        time += 100
    return files


def get_daily_filenames(prefix, experiment, file_type, year, time):
    """Create a list of filenames for a given directory, simulation,
    filetype, year, and time of day

    Arguments:
    prefix -- the directory containing the files
    experiment -- name of the simulation
    file_type -- which collection ex. tavg2d_aer_x
    year -- which year to generate files for
    time -- time of day of files
    """
    files = []
    for month, days_in_month in zip(months, days_in_months):
        for day in days[:days_in_month]:
            files.append(prefix + experiment + '.' + file_type + '.' + year +\
                    month + day + '_' + time + '.nc4')
    return files


def get_monthly_filenames(prefix, experiment, file_type, year):
    """Create a list of filenames for a given directory, simulation,
    filetype, year, and time of day

    Arguments:
    prefix -- the directory containing the files
    experiment -- name of the simulation
    file_type -- which collection ex. tavg2d_aer_x
    year -- which year to generate files for
    time -- time of day of files
    """
    files = []
    for month in months:
        files.append(prefix + experiment + '.' + file_type + '.monthly.' + year +\
                month + '.nc4')
    return files


def get_annual_filenames(prefix, experiment, file_type, month, first_year, last_year):
    """Create a list of filenames for a given directory, simulation,
    filetype, year, and time of day

    Arguments:
    prefix -- the directory containing the files
    experiment -- name of the simulation
    file_type -- which collection ex. tavg2d_aer_x
    year -- which year to generate files for
    time -- time of day of files
    """
    files = []
    for year in range(first_year, last_year):
        files.append(prefix + experiment + '.' + file_type + '.monthly.' +\
                str(year) + month + '.nc4')
    return files


def fetch_var(file, variable, fill_type='2d'):
    """Try to open a file and return a variable

    Arguments:
    file -- filename, like those generated by get_daily_filenames()
    variable -- variable name to retrieve
    """
    try:
        h5file = h5py.File(file, 'r')
    except Exception as Error:
        print(file)
        print(Error)
        if fill_type == '2d':
            data = np.zeros((1,181,288))
        elif fill_type == '3d':
            data = np.zeros((1,72,181,288))
        data[:] = np.nan
    try:
        data = h5file[variable]
    except Exception as Error:
        print(file)
        print(Error)
        if fill_type == '2d':
            data = np.zeros((1,181,288))
        elif fill_type == '3d':
            data = np.zeros((1,72,181,288))
        data[:] = np.nan
    data = data[:]
    #data[data > 1e10] = np.nan
    return np.asarray(data)


def fetch_units(file, variable, fill_type='2d'):
    """Try to open a file and return units

    Arguments:
    file -- filename, like those generated by get_daily_filenames()
    variable -- variable name to retrieve
    """
    try:
        h5file = h5py.File(file, 'r')
    except Exception as Error:
        print(file)
        print(Error)
        return
    try:
        data = h5file[variable]
    except Exception as Error:
        print(file)
        print(Error)
        return
    units = data.attrs['units']
    return units


def fetch_vars(file, variables):
    """Try to open a file and return a variable

    Arguments:
    file -- filename, like those generated by get_daily_filenames()
    variables -- list of variable names to retrieve
    """
    data = []
    try:
        h5file = h5py.File(file, 'r')
    except Exception as Error:
        print(file)
        print(Error)
        quit()
    try:
        for variable in variables:
            data.append(h5file[variable][:])
    except Exception as Error:
        print(file)
        print(Error)
        quit()
    data = np.asarray(data)
    data[data > 1e10] = np.nan
    return data
